name: Build and Push Base Docker image (parallel)

on:
  pull_request:
    paths:
      - 'base_image/**'
      - '.github/workflows/base-image.yml'
      - '.github/workflows/parallel-base-image.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.docker_meta.outputs.labels }}
      tags: ${{ steps.docker_meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: rnacentral/r2dt-base
          flavor: latest=false
          tags: |
            type=ref,event=pr

  build-stages:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [rscape, tRNAscan-SE, Bio-Easel, traveler, scripts, ribovore-infernal-easel]
    steps:
      - name: Build ${{ matrix.stage }} stage
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.stage }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: base_image/Dockerfile
          context: base_image/

  final-build:
    needs: build-stages
    runs-on: ubuntu-latest
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push final Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ needs.setup.outputs.labels }}
          tags: ${{ needs.setup.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: base_image/Dockerfile
          context: base_image/
