name: Tag rnacentral/r2dt-base image with given tag

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'Existing Image Tag'
        required: true
      destination_tag:
        description: 'Desired Image Version (Tag)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Retag the image to the given tag
      uses: LANsible/copy-image-manifest-action@main
      with:
        source:  rnacentral/r2dt-base@${{ github.event.inputs.source_tag }}
        targets: rnacentral/r2dt-base:${{ github.event.inputs.destination_tag }}
        wait_platforms: linux/amd64,linux/arm64
